# YOUR NAME OR TITLE OF YOUR SITE
name: Harsh Trivedi

# YOUR BRAND/PERSONAL TAGLINE
tagline: Howdy, I'm Dermot, here are my links

# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/harsh98trivedi.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # FACEBOOK
  - Name: Facebook
#   URL: https://www.facebook.com
#   Username: dermotcanniffe
#   Color: '#3b5998'
#   Icon-Class: fab fa-facebook

#   # INSTAGRAM
# - Name: Instagram
#   URL: https://www.instagram.com
#   Username: dermotcanniffe
#   Color: '#DD2A7B'
#   Icon-Class: fab fa-instagram

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: Derminator_IE
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

#   # CLUBHOUSE
# - Name: Clubhouse
#   URL: https://www.clubhouse.com
#   Username: '@dermotcanniffe'
#   Color: '#f1c40f'
#   Icon-Class: fas fa-hand-paper -mt-0.5
    
    # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/in
    Username: dermotcanniffe
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in

#   # YOUTUBE
# - Name: YouTube
#   URL: https://www.youtube.com/channel
#   Username: UCS3zvA_2r1iGT7MB3NVCGAw
#   Color: '#ff0000'
#   Icon-Class: fab fa-youtube

    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: dermotcanniffe
    Color: '#6e5494'
    Icon-Class: fab fa-github

#   # EMAIL
# - Name: Email
#   URL: 'mailto:harshtrivedi@duck.com'
#   Icon-Class: fas fa-envelope
#   Color: '#e17055'
#   Text_Color: '#ffffff'

#   # TWITCH
# - Name: Twitch
#   URL: 'https://twitch.tv'
#   Username: dermotcanniffe
#   Icon-Class: fab fa-twitch
#   Color: '#9147fe'
    Text_Color: '#ffffff'

#   # VIMEO
# - Name: Vimeo
#   URL: 'https://vimeo.com'
#   Username: harshtrivedi
#   Icon-Class: fab fa-vimeo-v
#   Color: '#1ab7ea'
    Text_Color: '#ffffff'

#   # MESSENGER
# - Name: Messenger
#   URL: https://m.me
#   Username: theharshtrivedi
#   Color: '#006AFF'
#   Icon-Class: fab fa-facebook-messenger

##   # REDDIT
# - Name: Reddit
#   URL: http://reddit.com/u
#   Username: harshtrivedi
#   Color: '#FF4500'
#   Icon-Class: fab fa-reddit-alien

##     # WHATSAPP
#   - Name: WhatsApp
#     URL: https://wa.me
#     Username: '+1123456789'
#     Color: '#25d366'
#     Icon-Class: fab fa-whatsapp

#   # TELEGRAM
# - Name: Telegram
#   URL: http://telegram.me
#   Username: theharshtrivedi
#   Color: '#0088cc'
#   Icon-Class: fab fa-telegram-plane

#   # SNAPCHAT
# - Name: Snapchat
#   URL: https://www.snapchat.com/add
#   Username: 'harsh98trivedi'
#   Color: '#FFFC00'
#   Text_Color: '#000000'
#    Icon-Class: fab fa-snapchat-ghost

#   # STEAM
# - Name: Steam
#   URL: https://steamcommunity.com/id
#   Username: 'harshtrivedi'
#   Color: '#66c0f4'
#   Text_Color: '#000000'
#Icon-Class: fab fa-steam

  #   # DISCORD
  # - Name: Discord
  #   URL: 'https://discord.gg'
  #   Username: 
  #   Icon-Class: fab fa-discord
  #   Color: '#5865F2'
  #   Text_Color: '#ffffff'

#  # PINTEREST
# - Name: Pinterest
#   URL: https://pinterest.com
#   Username: 'harsh98trivedi'
#   Color: '#E60023'
#   Icon-Class: fab fa-pinterest

#   # BEHANCE
# - Name: Behance
#   URL: https://www.behance.net
#   Username: dermotcanniffe
#   Color: '#1769ff'
#   Icon-Class: fab fa-behance

  #   # DRIBBBLE
  # - Name: Dribbble
  #   URL: https://dribbble.com
  #   Username: 
  #   Color: '#ea4c89'
  #   Icon-Class: fab fa-dribbble

#   # DEVIANTART
# - Name: DeviantArt
#   URL: https://www.deviantart.com
#   Username: harshtrivedi
#   Icon-Class: fab fa-deviantart
#   Color: '#05CC46'
#    Text_Color: '#ffffff'

#   # FIGMA
# - Name: Figma
#   URL: https://www.figma.com
#   Username: '@harshtrivedi'
#   Icon-Class: fab fa-figma
#   Color: '#ff2865'
#Text_Color: '#ffffff'

    # SPOTIFY
  - Name: Spotify
    URL: http://open.spotify.com/user
    Username: dermotcanniffe
    Color: '#1DB954'
    Icon-Class: fab fa-spotify

#   # SOUNDCLOUD
# - Name: SoundCloud
#   URL: https://www.soundcloud.com
#   Username: dermotcanniffe
#   Color: '#FE5000'
#   Icon-Class: fab fa-soundcloud

  #    # TIKTOK
  # - Name: TikTok
  #   URL: https://www.tiktok.com
  #   Username: 
  #   Color: '#FE2C55'
  #   Icon-Class: fab fa-tiktok

    # MEDIUM
  - Name: Medium
    URL: 'https://medium.com'
    Username: '@dermotcanniffe'
    Icon-Class: fab fa-medium-m
    Color: '#00ab6c'
    Text_Color: '#ffffff'

#   # DEV.TO
# - Name: Dev.to
#   URL: 'https://dev.to'
#   Username: dermotcanniffe
#   Icon-Class: fab fa-dev
#   Color: '#ffffff'
#    Text_Color: '#000000'

  #   # TUMBLR
  # - Name: Tumblr
  #   URL: https://www.tumblr.com
  #   Username: 
  #   Color: '#35465c'
  #   Icon-Class: fab fa-tumblr

# # BUY ME A COFFEE
# - Name: BuyMeACoffee
#   URL: 'https://buymeacoffee.com'
#   Username: harshtrivedi
#   Icon-Class: fas fa-mug-hot
#   Color: '#FFDD00'
#Text_Color: '#000000'

    ## CUSTOM LINK
  - Name: Mastodon
#    URL: https://hachyderm.io/@derminator
    URL: https://sw-development-is.social/@derminator
    Icon-Class: fas fa-link
    Color: '#ffb142'
    Text_Color: '#ffffff'

## - Name: Links
#   URL: https://github.com/harsh98trivedi/links
#   Icon-Class: fas fa-link
#   Color: '#d94869'
#   Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
