# YOUR NAME OR TITLE OF YOUR SITE
name: JackAce

# YOUR BRAND/PERSONAL TAGLINE
tagline: Gambler, Engineer, Hip Hop Connoisseur

# YOUR/BRAND IMAGE URL
Image_URL: https://avatars.githubusercontent.com/u/1430137?v=4

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://picsum.photos/1080?nocache=
# Cover_Image: /assets/images/jackace-background-5120x1440.png

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: jackacedotcom
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: JackAce
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

    # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/in
    Username: JackAce
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in

    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com
    Username: \@JackAceDotCom
    Color: '#ff0000'
    Icon-Class: fab fa-youtube

    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: JackAce
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # WordPress
  # - Name: WordPress.org
  #   URL: 'https://profiles.wordpress.org'
  #   Username: jackace
  #   Icon-Class: fa-brands fa-wordpress-simple
  #   Color: '#0073AA'
  #   Text_Color: '#ffffff'

    # EMAIL
  - Name: Email
    URL: 'mailto:jackace@jackace.com'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

    # TWITCH
  - Name: Twitch
    URL: 'https://twitch.tv'
    Username: jackacedotcom
    Icon-Class: fab fa-twitch
    Color: '#9147fe'
    Text_Color: '#ffffff'

    # VIMEO
  # - Name: Vimeo
  #   URL: 'https://vimeo.com'
  #   Username: jackace
  #   Icon-Class: fab fa-vimeo-v
  #   Color: '#1ab7ea'
  #   Text_Color: '#ffffff'

  #   # TELEGRAM
  # - Name: Telegram
  #   URL: http://telegram.me
  #   Username: jackace
  #   Color: '#0088cc'
  #   Icon-Class: fab fa-telegram-plane

    # DISCORD
  - Name: Discord
    URL: 'https://discord.gg'
    Username: R6nTPzcpma
    Icon-Class: fab fa-discord
    Color: '#5865F2'
    Text_Color: '#ffffff'

    # SOUNDCLOUD
  - Name: SoundCloud
    URL: https://www.soundcloud.com
    Username: jackacestudios
    Color: '#FE5000'
    Icon-Class: fab fa-soundcloud

     # TIKTOK
  - Name: TikTok
    URL: https://www.tiktok.com
    Username: \@jackace.com
    Color: '#FE2C55'
    Icon-Class: fab fa-tiktok

     # TIKTOK
  - Name: Patreon
    URL: https://www.patreon.com
    Username: jackace
    Color: '#FE2C55'
    Icon-Class: fab fa-patreon

  #   # MEDIUM
  # - Name: Medium
  #   URL: 'https://medium.com'
  #   Username: jackace
  #   Icon-Class: fab fa-medium-m
  #   Color: '#00ab6c'
  #   Text_Color: '#ffffff'

  # # BUY ME A COFFEE
  # - Name: BuyMeACoffee
  #   URL: 'https://buymeacoffee.com'
  #   Username: jackace
  #   Icon-Class: fas fa-mug-hot
  #   Color: '#FFDD00'
  #   Text_Color: '#000000'

  # Roulette Bet Analyzer
  - Name: JackAce's Web Site
    URL: https://www.jackace.com
    Icon-Class: fas fa-link
    Color: '#222222'
    Text_Color: '#ffffff'

  # Roulette Bet Analyzer
  - Name: Roulette Bet Analyzer
    URL: https://rba.jackace.com
    Icon-Class: fas fa-link
    Color: '#7dd34f'
    Text_Color: '#ffffff'

  - Name: Links
    URL: https://github.com/JackAce/links.jackace.com
    Icon-Class: fas fa-link
    Color: '#d94869'
    Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'No'

google_analytics: G-Q93BTYSCS6
google_adsense: ca-pub-5831288475713424

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
